name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy EO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Next
        run: pnpm build
          
      - name: Deploy to EdgeOne Pages
        run: npx edgeone pages deploy ./build -n home-page -t ${{ secrets.EDGEONE_API_TOKEN }}
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
